sudo: false
language: python
matrix:
  include:
    - env: TOXENV=py27-dj18
      python: 2.7
    - env: TOXENV=py34-dj18
      python: 3.4
    - env: TOXENV=py35-dj18
      python: 3.5
    - env: TOXENV=py27-dj19
      python: 2.7
    - env: TOXENV=py34-dj19
      python: 3.4
    - env: TOXENV=py35-dj19
      python: 3.5
    - env: TOXENV=flake8
      python: 2.7
install:
  - pip install tox 
script:
  - tox -e $TOXENV
